// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: equipment.sql

package db

import (
	"context"
)

const listEquipment = `-- name: ListEquipment :many
SELECT id, name, type, created_at
FROM equipment
ORDER BY id
`

func (q *Queries) ListEquipment(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
