// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID           int64              `json:"id"`
	EquipmentID  string             `json:"equipment_id"`
	Metric       string             `json:"metric"`
	RuleID       int32              `json:"rule_id"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	TriggerValue float64            `json:"trigger_value"`
}

type AlertRule struct {
	ID               int32   `json:"id"`
	Metric           string  `json:"metric"`
	Threshold        float64 `json:"threshold"`
	ConsecutiveCount int32   `json:"consecutive_count"`
}

type Equipment struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reading struct {
	ID          int64              `json:"id"`
	EventID     string             `json:"event_id"`
	EquipmentID string             `json:"equipment_id"`
	Metric      string             `json:"metric"`
	Value       float64            `json:"value"`
	Unit        string             `json:"unit"`
	RecordedAt  pgtype.Timestamptz `json:"recorded_at"`
	IngestedAt  pgtype.Timestamptz `json:"ingested_at"`
}
