// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// The caller must supply equal-length arrays, with matching indexes per event.
	InsertReadings(ctx context.Context, arg InsertReadingsParams) error
	ListAlertRules(ctx context.Context) ([]AlertRule, error)
	ListEquipment(ctx context.Context) ([]Equipment, error)
}

var _ Querier = (*Queries)(nil)
