// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReadings = `-- name: InsertReadings :exec
INSERT INTO readings (event_id, equipment_id, metric, value, unit, recorded_at)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::float8[]),
    unnest($5::text[]),
    unnest($6::timestamptz[])
ON CONFLICT (event_id) DO NOTHING
`

type InsertReadingsParams struct {
	EventIds      []string             `json:"event_ids"`
	EquipmentIds  []string             `json:"equipment_ids"`
	Metrics       []string             `json:"metrics"`
	ReadingValues []float64            `json:"reading_values"`
	Units         []string             `json:"units"`
	RecordedAts   []pgtype.Timestamptz `json:"recorded_ats"`
}

// The caller must supply equal-length arrays, with matching indexes per event.
func (q *Queries) InsertReadings(ctx context.Context, arg InsertReadingsParams) error {
	_, err := q.db.Exec(ctx, insertReadings,
		arg.EventIds,
		arg.EquipmentIds,
		arg.Metrics,
		arg.ReadingValues,
		arg.Units,
		arg.RecordedAts,
	)
	return err
}
